### ISSUE TITLE
NettyPgConnectionPool does not wait for shutdownGracefully to complete

### ISSUE THREAD

**Issue by Ryan-ZA** [alaisi/postgres-async-driver#15]
https://github.com/alaisi/postgres-async-driver/blob/master/src/main/java/com/github/pgasync/impl/netty/NettyPgConnectionPool.java#L49

shutdownGracefully returns a future, which is discarded. The future should either be completed before returning, or there should be a close method that returns the future.

This causes problems in cases where the process ends before the shutdown completes, causing non-closed connections to remain open on postgres.

**Comment by alaisi** [comment]
Verified, thanks for the bug report.

**Comment by alaisi** [comment]
Fixed in release 0.7.
