### ISSUE TITLE
Data can be sent to a wrong subscriber when pipeline is enabled

### ISSUE THREAD

**Issue by javadegava** [alaisi/postgres-async-driver#16]
Hi,

I found an error using the pool with the property pipeline enabled. With this feature connections are shared among multiple threads, but the class [`NettyPgProtocolStream`](https://github.com/alaisi/postgres-async-driver/blob/453e72a912bf3935fcf61ee78abe16e890710aee/src/main/java/com/github/pgasync/impl/netty/NettyPgProtocolStream.java#L104) is not threadsafe. In the method `send` it has the following lines: 

```java
pushSubscriber(subscriber);
write(messages);
```

With a very high concurrency may happen the following :

- Thread 1 pushes a subscriber.
- Thread 2 pushes a subscriber.
- Thread 2 writes the message.
- Thread 1 writes the message.

It's very strange, buy it can happen. If it happen, the response from the second thread is sended to the first subscriber. 

I did **150.000 requests** in less than a minute, and only got around **80 errors**, but it's a very ugly error.

I reproduced this error with something like this:

```java
/*
* There is no row.getDouble, and row.getBigDecimal crashes
* when the field is NUMERIC, so I had to use long.
* It's another issue hidden inside the issue. :)
*/
long random = (long)(Math.random()*10000000);
query = "SELECT " + random;
return getConnection()
    .queryRows(query)
    .doOnNext(row -> {
        long received = row.getLong(0);
        if( received != random  ){
            System.out.println(" Sent : " + random + " Received : " + received);
        }
    })
    .flatMap(t -> Observable.empty());
```

I did a quick fix synchronizing these lines : 

```java
synchronized (this) {
    pushSubscriber(subscriber);
    write(messages);
}
```

And the errors no longer happened.

I don't know if this is right for you, or you know some other way better to fix this.

**Comment by alaisi** [comment]
Thanks for the bug report! I'll try to come up with a way of fixing this by pushing the stateful operations always into nettys eventloop thread.

**Comment by javadegava** [comment]
:+1:

**Comment by alaisi** [comment]
Could you run the tests against the master to branch to see if the error still appears?

**Comment by javadegava** [comment]
Perfect! It doesn't happen any more. 

I knew there should be some kind of refactoring to avoid the use of synchronized.

:+1:
