### ISSUE TITLE
0.4 release

### ISSUE THREAD

**Issue by moea** [alaisi/postgres-async-driver#3]
Any chance of a release? I use this library + postgres.async at my day job, and it'd be great not to have to release my fork.

**Comment by alaisi** [comment]
Sure. I wanted to have LISTEN/NOTIFY support in the next release, but since my day job is currently taking pretty much all my time that will have to wait.

Java driver 0.4 and clojure 0.3.0 are now released (syncing to central). I added also array->vector conversion to the clojure implementation.
