### ISSUE TITLE
DataConverter.fromObject fail to cast primitive array to Object[]

### ISSUE THREAD

**Issue by henrik-lindqvist** [alaisi/postgres-async-driver#9]

**Comment by alaisi** [comment]
Fixed ClassCastException by throwing IllegalArgumentException instead. Primitive arrays are not supported at all due to pg allowing NULL values in arrays.

**Comment by henrik-lindqvist** [comment]
Why can't primitive arrays be allowed for input? Removing the cast works just fine.

**Comment by alaisi** [comment]
Sorry, I got only now what you meant by this issue. Primitive arrays should be allowed in INPUT but not in output. So the issue was most definitely valid and the cast is now removed.
